version: "3.1"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/robinson_server:latest
    command: make
    environment:
      DO_PAT: $DO_PAT
    volumes:
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
