name: Build and Test
on: push

jobs:
  actions:
    runs-on: ubuntu-latest
    env:
      github_sha: ${{ github.sha }}
    steps:
    - name: Copy repository
      uses: actions/checkout@v2
    - name: Build image
      run: docker build --tag islasgeci/robinson_server:latest --tag islasgeci/robinson_server:${github_sha:0:4} .
    - name: Check format
      run: docker run islasgeci/robinson_server:latest make check
    - name: Docker log-in
      env:
        docker_username: ${{ secrets.docker_username }}
        docker_password: ${{ secrets.docker_password }}
      run: echo "${docker_password}" | docker login -u "${docker_username}" --password-stdin
    - name: Upload image to Docker Hub
      run: docker push islasgeci/robinson_server:latest
    - name: Tag image with hash
      run: docker push islasgeci/robinson_server:${github_sha:0:4}
